version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5
    steps:
      - checkout
      - ruby/install-deps:
          key: repec-bundle
      - node/install:
          node-version: '12.22.5'

  test:
    docker:
      - image: cimg/ruby:2.7.5
        environment:
          APP_DB: repec
          APP_DB_USERNAME: user
          APP_DB_PASSWORD:
      - image: postgres:13
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: repec_test
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps:
          key: repec-bundle
      - node/install:
          node-version: '12.22.5'
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:migrate --trace
      - run:
          name: Run rspec
          command: bundle exec rspec
  brakeman:
    docker:
      - image: cimg/ruby:2.7.5
    steps:
      - checkout
      - ruby/install-deps:
          key: repec-bundle
      - run:
          name: Brakeman
          command: bundle exec brakeman

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - brakeman:
          requires:
            - build
