version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@5.0.0

jobs:
  build:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps:
          key: repec-bundle
      - node/install:
          node-version: '18.17.0'

  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
        environment:
          APP_DB: repec
          APP_DB_USERNAME: user
          APP_DB_PASSWORD:
      - image: postgres:15
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: repec_test
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps:
          key: repec-bundle
      - node/install:
          node-version: '18.17.0'
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:migrate --trace
      - run:
          name: Run rspec
          command: bundle exec rspec
  brakeman:
    docker:
      - image: cimg/ruby:3.1.3
    steps:
      - checkout
      - ruby/install-deps:
          key: repec-bundle
      - run:
          name: Brakeman
          command: bundle exec brakeman

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              ruby-version: ["3.1.3"]
      - test:
          requires:
            - build
          matrix:
            parameters:
              ruby-version: ["3.1.3"]
      - brakeman:
          requires:
            - build
